export const PRIORITY_INIT = 99
export const PRIORITY_SYSTEM_FREE_CREEPS = 98

export const PRIORITY_ROOM_CONTROL = 75
export const PRIORITY_ROOM_STRATEGY = 74
export const PRIORITY_ROOM_SOURCE_HARVEST = 60
export const PRIORITY_ROOM_STORAGE = 59
export const PRIORITY_ROOM_CONTROLLER_UPGRADE = 58
export const PRIORITY_ROOM_TOWER_CONTROL = 73

export const PRIORITY_ROLE_PIONEER = 50
export const PRIORITY_ROLE_HARVESTER = 55
export const PRIORITY_ROLE_UPGRADER = 54
export const PRIORITY_ROLE_BUILD = 55
